language: php

sudo: false

php:
    - 5.6
    - 7.0

install:
    - composer self-update -q
    - if [ -n "$GITHUB_OAUTH_TOKEN" ]; then composer config github-oauth.github.com ${GITHUB_OAUTH_TOKEN}; fi;
    - echo "{\"http-basic\":{\"repo.magento.com\":{\"username\":\"${MAGENTO_USERNAME}\",\"password\":\"${MAGENTO_PASSWORD}\"}}}" > auth.json
    - composer install --prefer-dist

script:
    - php vendor/bin/phpcs --standard=PSR2 Block/ Helper/ Model/
    - php vendor/bin/phpmd Block/,Helper/,Model/ text cleancode,codesize,controversial,design,naming,unusedcode
    - php vendor/bin/phpcpd Block/ Helper/ Model/ 
    - php vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
    - php vendor/bin/coveralls
    
